# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-01 20:14
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(blank=True, max_length=256, null=True)),
                ('archivo', models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['mp4', 'avi', 'mpeg', 'mov', 'wmv', 'flv', 'divx', 'mkv'])])),
                ('thumbnail', models.FileField(upload_to='thumbnails/', validators=[django.core.validators.FileExtensionValidator(['png', 'jpg', 'jpeg', 'gif'])])),
                ('busquedas', models.IntegerField(blank=True, default=0, null=True)),
                ('visitas', models.IntegerField(blank=True, default=0, null=True)),
                ('ruta', models.CharField(blank=True, max_length=100, null=True)),
                ('fecha_publicacion', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='XML',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(upload_to='')),
            ],
        ),
    ]
