# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-01-04 00:21
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Video', '0002_notificacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='xml',
            name='archivo',
            field=models.FileField(upload_to='', validators=[django.core.validators.FileExtensionValidator(['xml'])]),
        ),
    ]
